server:
  port: 8000
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.188.129
    port: 6379
  application:
    name: SCW-PROJECT
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/project/com.offcn.project.mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true
logging:
  level:
    com:
      offcn: debug
  file:
    path:  D:\log\scw-project.log
oss:
  endpoint: http://oss-cn-beijing.aliyuncs.com
  bucketDomain: zx-offcn-999.oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4G3bgsvEFXMjPtQaYUx6
  accessKeySecret: hYjiYeH9EPtdAnnI7Vafx2Nr9SvGQs
  bucketName: zx-offcn-999