server:
  port: 7000
spring:
  application:
    name: SCW-USER
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/atcrowdfunding?serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat  #开启监控过滤器
  redis:
    host: 192.168.188.129
    port: 6379
mybatis:
  mapper-locations: classpath:com.offcn.project.mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com:
      offcn: debug
  file:
    path:  D:\log\scw-user.log
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appcode: 3417ded5f97b4d9fb88cf0d321db15a0  #修改为自己的appcode